### ISSUE TITLE
DeiT mixup raise errors while training

### ISSUE THREAD

**Issue by xperzy** [xperzy/PPViT#40]
**Describe the bug**
Mixup raise ValueError when taking indices of bbox in Line 211 of mixup.py

**To Reproduce**
Start the training code, the error will happen after several iterations.

**Expected behavior**
no error occurs, the start and end index should not be the same while indexing in the array.

**Screenshots**
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/paddle/distributed/spawn.py", line 245, in _func_wrapper
    result = func(*args)
  File "/workspace/ppvit_github/PPViT/image_classification/DeiT/main_multi_gpu.py", line 393, in main_worker
    mixup_fn=mixup_fn)
  File "/workspace/ppvit_github/PPViT/image_classification/DeiT/main_multi_gpu.py", line 121, in train
    image, label = mixup_fn(image, label_orig)
  File "/workspace/ppvit_github/PPViT/image_classification/DeiT/mixup.py", line 174, in __call__
    lam = self._mix_batch(x)
  File "/workspace/ppvit_github/PPViT/image_classification/DeiT/mixup.py", line 211, in _mix_batch
    :, :, int(bbox_x1): int(bbox_x2), int(bbox_y1): int(bbox_y2)]
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 560, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) end should greater than start, but received end = 147, start = 147.
  [Hint: Expected end > start, but received end:147 <= start:147.] (at /paddle/paddle/fluid/operators/slice_op.cc:135)
  [operator < slice > error]

**Comment by xperzy** [comment]
This bug is fixed by https://github.com/xperzy/PPViT/blob/c61480c7c5b504abe73300857581e4acc05263e9/image_classification/DeiT/mixup.py#L218

So I close this issue
